[package]
authors.workspace = true
description = "A view that shows a map."
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "re_view_map"
publish = true
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true
include.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
re_data_ui = "0.26.2"
re_entity_db = "0.26.2"
re_log = "0.26.2"
re_log_types = "0.26.2"
re_query = "0.26.2"
re_renderer = "0.26.2"
re_view = "0.26.2"
re_tracing = "0.26.2"
re_types = "0.26.2"
re_ui = "0.26.2"
re_viewer_context = "0.26.2"
re_viewport_blueprint = "0.26.2"

macaw.workspace = true
bytemuck.workspace = true
egui.workspace = true
glam.workspace = true
itertools.workspace = true
walkers.workspace = true

[dev-dependencies]
re_test_context.workspace = true
